language: python

python:
  - "2.7"

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  - ODOO_VERSION=10 

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - ./travis_install_buildout

install:
  - bin/buildout -N -t 20

script:
  - bin/test_openerp -d openerp_test -i openacademy

after_success:

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - firefox --version
  - bin/travis-sphinx build
  - bin/travis-sphinx deploy
  - cp robot/config_80.py_template config_80.py
  - sed -i 's#ODOO_DB = "demo"#ODOO_DB = "openerp_test"#g' config_80.py
  - bin/start_openerp &
  - bin/pybot -v CONFIG:config_80.py robot/demo80.robot
