language: python

python:
  - "2.7"

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  - ODOO_VERSION=10 

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - ./travis_install_buildout

install:
  - bin/buildout -N -t 20

script:
  - bin/test_openerp -d openerp_test -i openacademy

after_success:

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b"
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes python="2.7" sphinx
  - pip install sphinx_bootstrap_theme
  - pip install --user travis-sphinx
  - travis-sphinx build
  - travis-sphinx deploy
