language: python

sudo: required

python:
  - 2.7

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

env:
  - ODOO_VERSION=10 

before_install:
  - ./dependencies.sh
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
  - bin/pip install -r requirements.txt
  - mv travis.cfg.in buildout.cfg 

install:
  - bin/buildout -N -t 20

script:
  - bin/test_openerp -d openerp_test -i open_academy
