language: python

python:
  - "2.7"

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  - VERSION="9.0" DOC="0" ROBOT="0"
  - VERSION="9.0" DOC="1" ROBOT="0"
  - VERSION="9.0" DOC="0" ROBOT="1"

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - firefox --version
  - ./travis_install_buildout

install:
  - bin/buildout -N -t 20

script:
  - ./travis_run_script

after_success:
  - bin/travis-sphinx deploy
#  - bin/start_openerp &
#  - bin/pybot -v CONFIG:config_80.py robot/demo80.robot
