language: python

sudo: false

python:
  - 2.7

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

env:
  - ODOO_VERSION=10 

before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
  - bin/pip install -r requirements.txt

install:
  - bin/buildout -N -t 20 -c travis.cfg

script:
  - bin/start_odoo
